# Importing Libraries

In [106]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

### Reading Dataset

In [107]:
df = pd.read_csv("C:\\Users\\Nagasai\\Downloads\\Data1.csv")#

In [108]:
df

User ID  Gender   Age  AnnualSalary Purchased
0        385    Male  35.0       20000.0        No
1        681    Male  40.0       43500.0        No
2        353    Male  49.0       74000.0        No
3        895    Male  40.0      107500.0       Yes
4        661    Male  25.0       79000.0        No
..       ...     ...   ...           ...       ...
995      863    Male  38.0       59000.0        No
996      800  Female  47.0       23500.0        No
997      407  Female  28.0      138500.0       Yes
998      299  Female  48.0      134000.0       Yes
999      687  Female  44.0       73500.0        No

[1000 rows x 5 columns]

# Seperating Dependent and Independent Variables

In [109]:
X = df.iloc[:, 1:-1].values
y = df.iloc[:, -1].values

In [110]:
X

array([['Male', 35.0, 20000.0],
       ['Male', 40.0, 43500.0],
       ['Male', 49.0, 74000.0],
       ...,
       ['Female', 28.0, 138500.0],
       ['Female', 48.0, 134000.0],
       ['Female', 44.0, 73500.0]], dtype=object)

In [111]:
y

array(['No', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No', 'No',
       'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes',
       'No', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes',
       'Yes', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No',
       'No', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No',
       'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes',
       'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No',
       'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes',
       'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No',
       'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No',
       'No', 'Yes', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes',
       'Yes', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No',
       'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes',
       'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Yes'

# Handling the Missing Values

In [112]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')#filling the missing values by average or mean
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

# Encoding the Categorical Data

In [113]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers=[('encoding', OneHotEncoder(),[0])],remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [114]:
X

array([[0.0, 1.0, 0.0, 35.0, 20000.0],
       [0.0, 1.0, 0.0, 40.0, 43500.0],
       [0.0, 1.0, 0.0, 49.0, 74000.0],
       ...,
       [1.0, 0.0, 0.0, 28.0, 138500.0],
       [1.0, 0.0, 0.0, 48.0, 134000.0],
       [1.0, 0.0, 0.0, 44.0, 73500.0]], dtype=object)

In [115]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [116]:
y

array([0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1,

# Dividing the Testset and Trainingset

In [117]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [121]:
X_train

array([[0.0, 1.0, 0.0, 19.0, 70000.0],
       [1.0, 0.0, 0.0, 53.0, 104000.0],
       [0.0, 1.0, 0.0, 39.0, 60500.0],
       ...,
       [0.0, 1.0, 0.0, 36.0, 54500.0],
       [1.0, 0.0, 0.0, 40.0, 76500.0],
       [1.0, 0.0, 0.0, 39.0, 114500.0]], dtype=object)

In [119]:
X_test

array([[1.0, 0.0, 0.0, 30.0, 79000.0],
       [1.0, 0.0, 0.0, 38.0, 79500.0],
       [0.0, 1.0, 0.0, 43.0, 77500.0],
       [1.0, 0.0, 0.0, 42.0, 73500.0],
       [0.0, 1.0, 0.0, 36.0, 92500.0],
       [0.0, 1.0, 0.0, 43.0, 72690.21190716448],
       [0.0, 1.0, 0.0, 42.0, 65000.0],
       [0.0, 1.0, 0.0, 43.0, 65500.0],
       [0.0, 1.0, 0.0, 36.0, 73500.0],
       [1.0, 0.0, 0.0, 40.0, 60500.0],
       [0.0, 1.0, 0.0, 26.0, 32000.0],
       [0.0, 1.0, 0.0, 57.0, 72500.0],
       [0.0, 1.0, 0.0, 19.0, 83500.0],
       [0.0, 1.0, 0.0, 39.0, 106000.0],
       [1.0, 0.0, 0.0, 36.0, 48500.0],
       [1.0, 0.0, 0.0, 36.0, 75000.0],
       [0.0, 1.0, 0.0, 26.0, 16000.0],
       [1.0, 0.0, 0.0, 46.0, 132500.0],
       [1.0, 0.0, 0.0, 22.0, 27000.0],
       [0.0, 1.0, 0.0, 47.0, 80500.0],
       [0.0, 1.0, 0.0, 42.0, 53500.0],
       [1.0, 0.0, 0.0, 41.0, 51000.0],
       [1.0, 0.0, 0.0, 37.0, 80000.0],
       [0.0, 1.0, 0.0, 32.0, 18000.0],
       [1.0, 0.0, 0.0, 21.0, 68000.0],
       [0.0, 

In [97]:
y_test

array([0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0])

In [98]:
y_train

array([0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1,

# Feature Scaling

In [122]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:,3:5] = sc.fit_transform(X_train[:, 3:5])
X_test[:, 3:5] = sc.fit_transform(X_test[:, 3:5])

In [123]:
X_train

array([[0.0, 1.0, 0.0, -2.00241941373311, -0.0950448943315108],
       [1.0, 0.0, 0.0, 1.2039769896196895, 0.8747859503183579],
       [0.0, 1.0, 0.0, -0.11630388234911032, -0.366027042101327],
       ...,
       [0.0, 1.0, 0.0, -0.39922121205671024, -0.5371736617454216],
       [1.0, 0.0, 0.0, -0.02199810577991033, 0.09036394361625823],
       [1.0, 0.0, 0.0, -0.11630388234911032, 1.1742925346955233]],
      dtype=object)

In [124]:
X_test

array([[1.0, 0.0, 0.0, -0.8776649499402589, 0.28531203127596644],
       [1.0, 0.0, 0.0, -0.14444582972901437, 0.3013820612651297],
       [0.0, 1.0, 0.0, 0.3138161204030135, 0.23710194130847664],
       [1.0, 0.0, 0.0, 0.2221637303766079, 0.10854170139517055],
       [0.0, 1.0, 0.0, -0.3277506097818255, 0.7192028409833745],
       [0.0, 1.0, 0.0, 0.3138161204030135, 0.08251506352170243],
       [0.0, 1.0, 0.0, 0.2221637303766079, -0.16464880842060492],
       [0.0, 1.0, 0.0, 0.3138161204030135, -0.14857877843144165],
       [0.0, 1.0, 0.0, -0.3277506097818255, 0.10854170139517055],
       [1.0, 0.0, 0.0, 0.03885895032379676, -0.3092790783230743],
       [0.0, 1.0, 0.0, -1.2442745100458812, -1.2252707877053803],
       [0.0, 1.0, 0.0, 1.5969495807726914, 0.07640164141684402],
       [0.0, 1.0, 0.0, -1.88584124023072, 0.4299423011784358],
       [0.0, 1.0, 0.0, -0.0527934397026088, 1.1530936506907827],
       [1.0, 0.0, 0.0, -0.3277506097818255, -0.6949597980629926],
       [1.0, 0.0, 0